definitions:
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  service.AuthResult:
    properties:
      token:
        type: string
    type: object
  service.ProfileResponse:
    properties:
      avatar_url:
        type: string
      coin:
        type: integer
      gender:
        type: string
      intro_long:
        type: string
      intro_short:
        type: string
      is_verified:
        type: boolean
      research_area:
        type: string
      tags:
        items:
          type: string
        type: array
      username:
        type: string
      uuid:
        type: string
    type: object
  service.UpdateProfileInput:
    properties:
      avatar_url:
        type: string
      gender:
        type: string
      intro_long:
        type: string
      intro_short:
        type: string
      is_verified:
        type: boolean
      research_area:
        type: string
      tags:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
  v1.EmailLoginRequest:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/email_login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 邮箱+验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.EmailLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/service.AuthResult'
              type: object
      summary: 邮箱验证码登录
      tags:
      - Auth
  /api/v1/auth/github_callback:
    get:
      consumes:
      - application/json
      parameters:
      - description: GitHub回调Code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/service.AuthResult'
              type: object
      summary: GitHub登录回调, 前端不调用该API
      tags:
      - Auth
  /api/v1/auth/google_callback:
    get:
      consumes:
      - application/json
      parameters:
      - description: Google回调Code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/service.AuthResult'
              type: object
      summary: Google登录回调
      tags:
      - Auth
  /api/v1/profile:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/service.ProfileResponse'
              type: object
      summary: 获取用户Profile
      tags:
      - Profile
    post:
      consumes:
      - application/json
      parameters:
      - description: 需要更新的字段
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.UpdateProfileInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 更新用户Profile（部分字段）
      tags:
      - Profile
  /test:
    get:
      consumes:
      - application/json
      description: 测试前后端联通性
      parameters:
      - description: ping
        in: query
        name: data
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "pong", "success": true}'
          schema:
            type: string
      summary: 测试前后端联通性
      tags:
      - 测试
swagger: "2.0"
