definitions:
  database.User:
    properties:
      avatar_url:
        type: string
      coin:
        type: integer
      created_at:
        description: 创建时间
        type: string
      gender:
        description: 可选 Male/Female/Other
        type: string
      intro_long:
        description: 个人简介
        type: string
      intro_short:
        description: 个人简介 格言
        type: string
      is_verified:
        description: 是否已认证教育邮箱
        type: boolean
      username:
        description: 用户名
        type: string
      uuid:
        description: 用户唯一标识
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  service.AuthResult:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/database.User'
    type: object
  v1.EmailLoginRequest:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/email_login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 邮箱+验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.EmailLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/service.AuthResult'
              type: object
      summary: 邮箱验证码登录
      tags:
      - Auth
  /api/v1/auth/github_callback:
    get:
      consumes:
      - application/json
      parameters:
      - description: GitHub回调Code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/service.AuthResult'
              type: object
      summary: GitHub登录回调
      tags:
      - Auth
  /test:
    get:
      consumes:
      - application/json
      description: 测试前后端联通性
      parameters:
      - description: ping
        in: query
        name: data
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "pong", "success": true}'
          schema:
            type: string
      summary: 测试前后端联通性
      tags:
      - 测试
swagger: "2.0"
